logging_params:
  log_dir: "logs"
  name: "toy_run"

schedules_path: "examples/data/synthetic_schedules.csv"

encoder_params:
  name: "discrete"
  duration: 1440
  step_size: 10

model_params:
  name: "VAEDiscCNN2D"
  hidden_layers: [64,64]
  latent_dim: 2
  stride: [2,2]

loader_params:
  train_batch_size: 32
  val_batch_size:  32
  num_workers: 3

experiment_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025

trainer_params:
  max_epochs: 2

seed: 1234
  