seed: 12345

logging_params:
  log_dir: "logs/vae_paper"
  name: "koushik2"

schedules_path: "tmp/nts_schedules_2023.csv"
attributes_path: "tmp/nts_attributes_2023.csv"

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8
  val_split: 0.1

trainer_params:
  min_epochs: 50
  max_epochs: 200
  patience: 20

experiment_params:
  LR: 0.001
  weight_decay: 0.02
  scheduler_gamma: 0.975

labels_encoder:
    labels:
      work_status: nominal
      area: nominal
      age_group: nominal
      mobility: nominal
      income: ordinal
      education: nominal
      ethnicity: nominal
      gender: nominal
      car_access: nominal
      license: nominal
      WfH: nominal
      wheelchair_user: nominal
      ticket_holder: nominal
      health: nominal
      blue_badge: nominal
      num_license_holders: nominal

evaluation_params:
  split_on: [gender, age_group, car_access, work_status, income]

encoder_params:
  name: "discrete"
  weighting: act_inverse
  step_size: 10
  duration: 1440
  jitter: 0.0
  
model_params:
  name: "CondDiscLSTM"
  latent_dim: 0
  hidden_n: 3
  hidden_size: 200
  dropout: 0.2
  bidirectional: True

