seed: 12345

logging_params:
  log_dir: "logs/actvae"
  name: "conditional"

schedules_path: "~/Data/foundata/out/nts/2023/activities.csv"
attributes_path: "~/Data/foundata/out/nts/2023/attributes_binned.csv"

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8
  val_split: 0.1

trainer_params:
  min_epochs: 50
  max_epochs: 300
  patience: 50

experiment_params:
  LR: 0.001
  weight_decay: 0.01
  scheduler_gamma: 0.98
  duration_loss_weight: 200

labels_encoder:
  name: "tokens"
  weighting: unit
  joint_weighting: inverse
  labels:
    age: nominal
    sex: nominal
    employment: nominal
    hh_income: nominal
    hh_zone: nominal
    day: nominal
    vehicles: nominal
    access_egress_distance: nominal

evaluation_params:
  split_on: [age, sex, employment, hh_income, hh_zone, day, vehicles, access_egress_distance]


encoder_params:
  name: "continuous"
  max_length: 16
  norm_duration: 1440
  jitter: 0.1
  fix_durations: stretch
  weighting: unit
  joint_weighting: unit
  label_weighting: unit
  trim_eos: True
  
model_params:
  name: "CondContLSTM"
  latent_dim: 0
  hidden_n: 4
  hidden_size: 128
  labels_hidden_size: 32
  dropout: 0.0
  top_sampler: True

