seed: 12345

logging_params:
  log_dir: "logs/actvae"
  name: "vae"

schedules_path: "~/Data/foundata/out/nts/2023/activities.csv"
attributes_path: "~/Data/foundata/out/nts/2023/attributes_binned.csv"

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8
  val_split: 0.1

trainer_params:
  min_epochs: 50
  max_epochs: 300
  patience: 50
  collapse_monitoring:
    enabled: False

encoder_params:
  name: "continuous"
  fix_durations: stretch
  max_length: 16
  duration: 1440
  jitter: 0
  weighting: unit
  joint_weighting: unit
  trim_eos: True

labels_encoder:
  name: "tokens"
  weighting: unit
  joint_weighting: inverse
  labels:
    age: nominal
    sex: nominal
    employment: nominal
    hh_income: nominal
    hh_zone: nominal
    day: nominal
    vehicles: nominal
    access_egress_distance: nominal

evaluation_params:
  split_on: [age, sex, employment, hh_income, hh_zone, day, vehicles, access_egress_distance]

experiment_params:
  LR: 0.001
  weight_decay: 0.01
  scheduler_gamma: 0.98
  kld_weight: 0.01
  duration_loss_weight: 200

model_params:
  name: "VAEContLSTM"
  latent_dim: 6
  hidden_n: 4
  hidden_size: 256
  dropout: 0
