seed: 12345

logging_params:
  log_dir: "logs/TRB"
  name: "discrim"

schedules_path: "tmp/nts_home_schedules.csv"
attributes_path: "tmp/nts_home_attributes_groups.csv"

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  min_epochs: 40
  max_epochs: 100
  patience: 20

experiment_params:
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

conditionals:
  gender: nominal
  age_group: nominal
  car_access: nominal
  work_status: nominal
  income: ordinal

encoder_params:
  name: "discrete"
  step_size: 10
  duration: 1440
  jitter: 0.2
  
model_params:
  name: "CondDiscLSTM"
  latent_dim: 0
  hidden_n: 2
  hidden_size: 128
  dropout: 0.2
  bidirectional: True
