global:

  logging_params:
    log_dir: "logs/TRB"
    name: "vae"

  schedules_path: "tmp/nts_schedules_2023.csv"
  attributes_path: "tmp/nts_attributes_2023.csv"

  evaluation_params:
    split_on: [gender, age_group, car_access, work_status, income]

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8
    val_split: 0.1
    test_split: 0.1


  trainer_params:
    min_epochs: 50
    max_epochs: 200
    patience: 50

  encoder_params:
    name: "continuous"
    fix_durations: True
    max_length: 16
    duration: 1440
    jitter: 0.1
    weighting: unit
    joint_weighting: unit
    trim_eos: True

  experiment_params:
    LR: 0.001
    weight_decay: 0.02
    scheduler_gamma: 0.975
    kld_weight: 0.01
    duration_loss_weight: 200

  model_params:
    name: "VAEContLSTM"
    latent_dim: 6
    hidden_n: 4
    hidden_size: 256
    dropout: 0.1

vae_nrun0:
  seed: 12345

vae_nrun1:
  seed: 12345

vae_nrun2:
  seed: 12345

vae_nrun3:
  seed: 12345

vae_nrun4:  
  seed: 12345

