global:
  logging_params:
    save_dir: "logs_cond"
    name: "test"

  schedules_path: "examples/tmp/schedules.csv"

  loader_params:
    train_batch_size: 256
    val_batch_size:  256
    num_workers: 3

  trainer_params:
    max_epochs: 100

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95

  seed: 1234

L6_uncond:
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  model_params:
    name: "LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.1
    kld_weight: 0.001

L12_uncond:
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  model_params:
    name: "LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 12
    dropout: 0.1
    kld_weight: 0.001

L6_cond:
  attributes_path: "examples/tmp/attributes.csv"
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  conditionals:
    gender: nominal
    age: {ordinal: [0, 100]}
    employment: nominal
  model_params:
    name: "conditional_LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.1
    kld_weight: 0.001

L12_cond:
  attributes_path: "examples/tmp/attributes.csv"
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  conditionals:
    gender: nominal
    age: {ordinal: [0, 100]}
    employment: nominal
  model_params:
    name: "conditional_LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 12
    dropout: 0.1
    kld_weight: 0.001