global:
  seed: 1234
  logging_params:
    log_dir: "toy_logs"
    name: "realistic_toy"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes.csv"
  loader_params:
    train_batch_size: 512
    val_batch_size:  512
    num_workers: 12

  trainer_params:
    min_epochs: 20
    max_epochs: 100
    patience: 10

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95

  conditionals:
    # gender: nominal
    # age: nominal
    # ethnicity: nominal
    # education: nominal
    # license: nominal
    # car_access: nominal
    work_status: nominal
    # area: nominal
    # income: ordinal
    # hh_size: ordinal
    # hh_composition: nominal
    # hh_children: ordinal
    # hh_cars: ordinal
    # hh_bikes: ordinal
    # hh_motorcycles: ordinal
  
  evaluation_params:
    split_on: [work_status]
  
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.1

# DiscLSTM:
#   encoder_params:
#     name: "discrete"
#     step_size: 5
#     duration: 1440
#     jitter: 0.2
#   model_params:
#     name: "CondDiscLSTM"
#     latent_dim: 6
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.2
#     bidirectional: True

CVAESeqLSTM_6x6x512_kld0005:
  model_params:
    name: "CVAESeqLSTMAll"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.0005

CVAESeqLSTM_6x6x512_kld0005_nudge:
  model_params:
    name: "CVAESeqLSTMNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.0005

# CVAESeqLSTM_6x6x512_kld001:
#   model_params:
#     name: "CVAESeqLSTMAll"
#     latent_dim: 6
#     hidden_layers: 6
#     hidden_size: 512
#     dropout: 0.0
#     kld_weight: 0.001

CVAESeqLSTM_6x6x512_kld005:
  model_params:
    name: "CVAESeqLSTMAll"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.005

CVAESeqLSTM_6x6x512_kld005_nudge:
  model_params:
    name: "CVAESeqLSTMNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.005

# CVAESeqLSTM_6x6x512_kld01:
#   model_params:
#     name: "CVAESeqLSTMAll"
#     latent_dim: 6
#     hidden_layers: 6
#     hidden_size: 512
#     dropout: 0.0
#     kld_weight: 0.01

CVAESeqLSTM_6x6x512_kld05:
  model_params:
    name: "CVAESeqLSTMAll"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.05

CVAESeqLSTM_6x6x512_kld05_nudge:
  model_params:
    name: "CVAESeqLSTMNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.05
    
CVAESeqLSTM_6x6x512_kld1:
  model_params:
    name: "CVAESeqLSTMAll"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.1

CVAESeqLSTM_6x6x512_kld1_nudge:
  model_params:
    name: "CVAESeqLSTMNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.0
    kld_weight: 0.1

# CVAESeqLSTM_6x6x512_kld5:
#   model_params:
#     name: "CVAESeqLSTMAll"
#     latent_dim: 6
#     hidden_layers: 6
#     hidden_size: 512
#     dropout: 0.0
#     kld_weight: 0.5

# CVAESeqLSTM_6x6x512_kld10:
#   model_params:
#     name: "CVAESeqLSTMAll"
#     latent_dim: 6
#     hidden_layers: 3
#     hidden_size: 256
#     dropout: 0.0
#     kld_weight: 1.0

# CVAESeqLSTM_6x6x512_kld10_nudge:
#   model_params:
#     name: "CVAESeqLSTMNudge"
#     latent_dim: 6
#     hidden_layers: 3
#     hidden_size: 256
#     dropout: 0.0
#     kld_weight: 1.0

# VAESeqLSTM_XXXL:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 6
#     hidden_layers: 7
#     hidden_size: 1024
#     dropout: 0.2
# VAESeqLSTM_XXXXL:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 6
#     hidden_layers: 8
#     hidden_size: 1024
#     dropout: 0.2