global:
  seed: 1234
  logging_params:
    log_dir: "logs/cvaes"
    name: "test"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"

  attribute_encoder: "tokens"

  conditionals:
    gender: nominal
    age_group: nominal
    car_access: nominal
    work_status: nominal
    income: nominal

  evaluation_params:
    split_on: [gender, age_group, car_access, work_status, income]

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  trainer_params:
    min_epochs: 10
    max_epochs: 200
    patience: 10

  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.1
    fix_durations: True

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.01

InputsConcatInputsAdd:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs_add
    latent_conditionality: concat
    decoder_conditionality: inputs_add

InputsAddInputsAdd:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs_add
    latent_conditionality: add
    decoder_conditionality: inputs_add

InputsConcatInputsConcat:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs_concat
    latent_conditionality: concat
    decoder_conditionality: inputs_concat

InputsAddInputsConcat:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs_concat
    latent_conditionality: add
    decoder_conditionality: inputs_concat

BothAddConcatInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both_add
    latent_conditionality: concat
    decoder_conditionality: inputs_add

BothAddAddInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both_add
    latent_conditionality: add
    decoder_conditionality: inputs_add

BothConcatConcatInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both_concat
    latent_conditionality: concat
    decoder_conditionality: inputs_add

BothConcatAddInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both_concat
    latent_conditionality: add
    decoder_conditionality: inputs_add