global:
  seed: 12345
  logging_params:
    log_dir: "logs/cvaes"
    name: "klds"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"

  attribute_encoder:
    name: "tokens"
    weighting: "unit"
    joint_weighting: "unit"

  conditionals:
    gender: nominal
    age_group: nominal
    car_access: nominal
    work_status: nominal
    income: nominal

  # evaluation_params:
  #   split_on: [gender, age_group, car_access, work_status, income]

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.0
    fix_durations: True
    trailing_weights: True
    weighting: unit
    joint_weighting: unit

  trainer_params:
    min_epochs: 100
    max_epochs: 100
    patience: 100

  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 512
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both_add
    latent_conditionality: add
    decoder_conditionality: inputs_add


kld0_001d100:
  experiment_params:
    LR: 0.0005
    weight_decay: 0.02
    scheduler_gamma: 0.975
    kld_weight: 0.001
    duration_loss_weight: 100

kld0_002d100:
  experiment_params:
    LR: 0.0005
    weight_decay: 0.02
    scheduler_gamma: 0.975
    kld_weight: 0.002
    duration_loss_weight: 100

kld0_004d100:
  experiment_params:
    LR: 0.0005
    weight_decay: 0.02
    scheduler_gamma: 0.975
    kld_weight: 0.004
    duration_loss_weight: 100

kld0_008d100:
  experiment_params:
    LR: 0.0005
    weight_decay: 0.02
    scheduler_gamma: 0.975
    kld_weight: 0.008
    duration_loss_weight: 100
