global:
  seed: 1234
  logging_params:
    log_dir: "logs/cvaes"
    name: "test"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"
  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 4

  trainer_params:
    min_epochs: 10
    max_epochs: 200
    patience: 10

  conditionals:
    gender: nominal
    age_group: nominal
    car_access: nominal
    work_status: nominal
    income: nominal

  attribute_encoder: "tokens"

  evaluation_params:
    split_on: [work_status]

  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.1
    fix_durations: True

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.01
    label_loss_weight: 0.0001

NoneConcatNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: none
    latent_conditionality: concat
    decoder_conditionality: none

NoneAddNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: none

HiddenConcatNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: hidden
    latent_conditionality: concat
    decoder_conditionality: none

HiddenAddNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: hidden
    latent_conditionality: add
    decoder_conditionality: none

InputsConcatNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs
    latent_conditionality: concat
    decoder_conditionality: none

InputsAddNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs
    latent_conditionality: add
    decoder_conditionality: none

BothConcatNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both
    latent_conditionality: concat
    decoder_conditionality: none

BothAddNone:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both
    latent_conditionality: add
    decoder_conditionality: none

NoneConcatInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: none
    latent_conditionality: concat
    decoder_conditionality: inputs

NoneAddInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: inputs

HiddenConcatInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: hidden
    latent_conditionality: concat
    decoder_conditionality: inputs

HiddenAddInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: hidden
    latent_conditionality: add
    decoder_conditionality: inputs

InputsConcatInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs
    latent_conditionality: concat
    decoder_conditionality: inputs

InputsAddInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: inputs
    latent_conditionality: add
    decoder_conditionality: inputs

BothConcatInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both
    latent_conditionality: concat
    decoder_conditionality: inputs

BothAddInputs:
  model_params:
    name: "CVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5
    encoder_conditionality: both
    latent_conditionality: add
    decoder_conditionality: inputs
