global:
  seed: 1234
  logging_params:
    log_dir: "logs/cvaes"
    name: "batch"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"
  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 4

  trainer_params:
    min_epochs: 20
    max_epochs: 100
    patience: 10

  conditionals:
    gender: nominal
    age_group: nominal
    car_access: nominal
    work_status: nominal
    income: nominal

  attribute_encoder: "tokens"

  evaluation_params:
    split_on: [work_status]

  encoder_params:
    name: "sequence"
    max_length: 12
    norm_duration: 1440
    jitter: 0.1
    fix_durations: True

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.01
    label_loss_weight: 0.0001

Latent:
  model_params:
    name: "CVAESeqLSTM"
    hidden_layers: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5

LatentPre:
  model_params:
    name: "CVAESeqLSTMPre"
    hidden_layers: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5

Feed:
  model_params:
    name: "CVAESeqLSTMFeed"
    hidden_layers: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5

FeedPre:
  model_params:
    name: "CVAESeqLSTMFeedPre"
    hidden_layers: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5

LatentFeed:
  model_params:
    name: "CVAESeqLSTMLatentFeed"
    hidden_layers: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5

LatentFeedPre:
  model_params:
    name: "CVAESeqLSTMLatentFeedPre"
    hidden_layers: 5
    hidden_size: 256
    labels_hidden_size: 32
    latent_dim: 6
    dropout: 0.1
    teacher_forcing_ratio: 0.5

# LatentAddFeed:
#   model_params:
#     name: "CVAESeqLSTMLatentAddFeed"
#     hidden_layers: 5
#     hidden_size: 256
#     labels_hidden_size: 32
#     latent_dim: 6
#     dropout: 0.1
#     teacher_forcing_ratio: 0.5

# LatentAddFeedPre:
#   model_params:
#     name: "CVAESeqLSTMLatentAddFeedPre"
#     hidden_layers: 5
#     hidden_size: 256
#     labels_hidden_size: 32
#     latent_dim: 6
#     dropout: 0.1
#     teacher_forcing_ratio: 0.5

# After:
#   model_params:
#     name: "CVAESeqLSTMAfter"
#     hidden_layers: 5
#     hidden_size: 256
#     labels_hidden_size: 32
#     latent_dim: 6
#     dropout: 0.1
#     teacher_forcing_ratio: 0.5

# All:
#   model_params:
#     name: "CVAESeqLSTMAll"
#     hidden_layers: 5
#     hidden_size: 256
#     labels_hidden_size: 32
#     latent_dim: 6
#     dropout: 0.1
#     teacher_forcing_ratio: 0.5

# Nudge:
#   model_params:
#     name: "CVAESeqLSTMNudge"
#     hidden_layers: 5
#     hidden_size: 256
#     labels_hidden_size: 32
#     latent_dim: 6
#     dropout: 0.1
#     teacher_forcing_ratio: 0.5

# DoubleNudge:
#   model_params:
#     name: "CVAESeqLSTMDoubleNudge"
#     hidden_layers: 5
#     hidden_size: 256
#     labels_hidden_size: 32
#     latent_dim: 6
#     dropout: 0.1
#     teacher_forcing_ratio: 0.5

# NudgeAdv:
#   model_params:
#     name: "CVAESeqLSTMNudgeAdv"
#     hidden_layers: 5
#     hidden_size: 256
#     labels_hidden_size: 32
#     latent_dim: 6
#     dropout: 0.1
#     teacher_forcing_ratio: 0.5
