global:
  seed: 1234
  logging_params:
    log_dir: "logs"
    name: "discrete_models"
  
  schedules_path: "tmp/nts_home_schedules.csv"
  # attributes_path: "tmp/nts_home_attributes_groups.csv"

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8
  
  trainer_params:
    min_epochs: 50
    max_epochs: 200
    patience: 20
  
  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.002
  
  encoder_params:
    name: "discrete"
    duration: 1440
    step_size: 10

cnn1d:
  model_params:
    name: "VAEDiscCNN1D"
    latent_dim: 6
    hidden_layers: [256,256,256,256,256,256]
    dropout: 0.0
    stride: 2
    kernel_size: 2
    padding: 0

fc:
  model_params:
    name: "VAEDiscFC"
    latent_dim: 6
    hidden_layers: [128,32] 
    dropout: 0.1

# cnn2d:
#   model_params:
#     name: "VAEDiscConv"
#     latent_dim: 6
#     hidden_layers: [256,256,256,256,256,256] 
#     dropout: 0.1

rnn:
  model_params:
    name: "VAEDiscLSTM"
    latent_dim: 6
    hidden_n: 4
    hidden_size: 128
    dropout: 0.1

