global:
  schedules_path: "examples/data/synthetic_schedules.csv"
  attributes_path: "examples/data/synthetic_attributes.csv"
  logging_params:
    log_dir: "logs"
    name: "conditionals_toy_batch"
  loader_params:
    train_batch_size: 32
    val_batch_size:  32
    num_workers: 12
  trainer_params:
    max_epochs: 5
    patience: 5
  conditionals:
    gender: nominal
    age: {ordinal: [0,100]}
    employment: nominal
  evaluation_params:
    split_on: [gender, employment]
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
  seed: 1234

conditional_only:
  encoder_params:
    name: "sequence_staggered"
    max_length: 16
    norm_duration: 1440
    jitter: 0.1
  model_params:
    name: "C_LSTM"
    hidden_layers: 1
    hidden_size: 32
    latent_dim: 6
    dropout: 0.1

standard_vae:
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.3
  model_params:
    name: "VAE_LSTM"
    hidden_layers: 4
    hidden_size: 128
    latent_dim: 6
    dropout: 0.3
    kld_weight: 0.001

conditional_vae:
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  model_params:
    name: "CVAE_LSTM"
    hidden_layers: 4
    hidden_size: 512
    latent_dim: 6
    dropout: 0.3
    kld_weight: 0.001