logging_params:
  log_dir: "logs"
  name: "toy_conditional"

schedules_path: "examples/data/synthetic_schedules.csv"
attributes_path: "examples/data/synthetic_attributes.csv"

conditionals:
  gender: nominal
  age: {ordinal: [0,100]}
  employment: nominal

encoder_params:
  name: "sequence_staggered"
  max_length: 16
  norm_duration: 1440
  jitter: 0.1

model_params:
  name: "CVAESeqLSTM"
  hidden_layers: 1
  hidden_size: 32
  latent_dim: 6
  dropout: 0.1
  teacher_forcing_ratio: 0.5

loader_params:
  train_batch_size: 32
  val_batch_size:  32
  num_workers: 3

experiment_params:
  LR: 0.01
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025

trainer_params:
  patience: 3
  max_epochs: 10

seed: 1234
  