global:
  schedules_path: "examples/data/synthetic_schedules.csv"
  logging_params:
    log_dir: "logs"
    name: "steps"
  seed: 1234

  loader_params:
    train_batch_size: 128
    val_batch_size:  128
    num_workers: 3

  experiment_params:
    LR: 0.005
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.00025

  trainer_params:
    max_epochs: 1

  model_params:
    name: "VAE_Conv_Discrete"
    hidden_layers: [64,64]
    latent_dim: 2
    stride: [2,2]

step10:
  encoder_params:
    name: "discrete"
    duration: 1440
    step_size: 10

step5:
  encoder_params:
    name: "discrete"
    duration: 1440
    step_size: 5


