global:
  logging_params:
    log_dir: "logs"
    name: "joint_model_Z24"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes.csv"

  conditionals:
    gender: nominal
    age: nominal
    # ethnicity: nominal
    # education: nominal
    # license: nominal
    car_access: nominal
    work_status: nominal
    # area: nominal
    income: nominal
    hh_size: nominal
    # hh_composition: nominal
    # hh_children: ordinal
    # hh_cars: ordinal
    # hh_bikes: ordinal
    # hh_motorcycles: ordinal

  evaluation_params:
    split_on: [gender, age, car_access, work_status]

  attribute_encoder: "tokens"

  encoder_params:
    name: "sequence"
    max_length: 12
    norm_duration: 1440
    jitter: 0.2

  model_params:
    name: "JVAESeqLSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 24
    dropout: 0.1
    teacher_forcing_ratio: 0.5

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  trainer_params:
    min_epochs: 30
    patience: 30
    max_epochs: 100

  seed: 1234

atts0_kld01:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.01
    attribute_loss_weight: 0.0

atts00001kld01:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.01
    attribute_los_weight: 0.00001

atts0001kld01:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.01
    attribute_los_weight: 0.0001

atts0_kld001:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.001
    attribute_loss_weight: 0.0

atts00001kld001:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.001
    attribute_los_weight: 0.00001

atts0001kld001:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.001
    attribute_los_weight: 0.0001

atts0_kld0001:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.0001
    attribute_loss_weight: 0.0

atts00001kld0001:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.0001
    attribute_los_weight: 0.00001

atts0001kld0001:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_loss_weight: 0.0001
    attribute_los_weight: 0.0001

