global:
  seed: 1234
  logging_params:
    log_dir: "experiments"
    name: "experiments10"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes.csv"

  loader_params:
    train_batch_size: 512
    val_batch_size:  512
    num_workers: 12

  trainer_params:
    min_epochs: 20
    max_epochs: 100
    patience: 10

  experiment_params:
    test_z: True
    LR: 0.0001
    weight_decay: 0.0
    scheduler_gamma: 0.95

  conditionals:
    # gender: nominal
    # age: nominal
    # ethnicity: nominal
    # education: nominal
    # license: nominal
    # car_access: nominal
    work_status: nominal
    # area: nominal
    # income: ordinal
    # hh_size: ordinal
    # hh_composition: nominal
    # hh_children: ordinal
    # hh_cars: ordinal
    # hh_bikes: ordinal
    # hh_motorcycles: ordinal
  
  evaluation_params:
    split_on: [gender, age, ethnicity, education, license, car_access, work_status]
  
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2

# DiscLSTM:
#   encoder_params:
#     name: "discrete"
#     step_size: 5
#     duration: 1440
#     jitter: 0.2
#   model_params:
#     name: "CondDiscLSTM"
#     latent_dim: 6
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.2
#     bidirectional: True

# CVAESeqLSTM_6x512_L6kld10000:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 6
#     hidden_layers: 6
#     hidden_size: 512
#     dropout: 0.2
#   experiment_params:
#     LR: 0.0001
#     weight_decay: 0.0
#     scheduler_gamma: 0.95
#     kld_weight: 1.0

# CVAESeqLSTM_6x512_L6kld100:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 6
#     hidden_layers: 6
#     hidden_size: 512
#     dropout: 0.2
#   experiment_params:
#     LR: 0.0001
#     weight_decay: 0.0
#     scheduler_gamma: 0.95
#     kld_weight: 0.01

# CVAESeqLSTM_6x512_L6kld1:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 6
#     hidden_layers: 6
#     hidden_size: 512
#     dropout: 0.2
#   experiment_params:
#     LR: 0.0001
#     weight_decay: 0.0
#     scheduler_gamma: 0.95
#     kld_weight: 0.0001

CVAESeqLSTM_7x1024_L6:
  model_params:
    name: "CVAESeqLSTM2"
    latent_dim: 6
    hidden_layers: 7
    hidden_size: 1024
    dropout: 0.2
  experiment_params:
    test_z: True
    LR: 0.0001
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.0001

# VAESeqLSTM_XXXL:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 6
#     hidden_layers: 7
#     hidden_size: 1024
#     dropout: 0.2
# VAESeqLSTM_XXXXL:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 6
#     hidden_layers: 8
#     hidden_size: 1024
#     dropout: 0.2