global:
  seed: 1234
  logging_params:
    log_dir: "experiments"
    name: "experiments"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes.csv"

  loader_params:
    train_batch_size: 256
    val_batch_size:  256
    num_workers: 12

  trainer_params:
    min_epochs: 20
    max_epochs: 100
    patience: 10

  experiment_params:
    LR: 0.0001
    weight_decay: 0.0
    scheduler_gamma: 0.95

  conditionals:
    gender: nominal
    age: nominal
    ethnicity: nominal
    education: nominal
    license: nominal
    car_access: nominal
    work_status: nominal
    area: nominal
    income: ordinal
    hh_size: ordinal
    hh_composition: nominal
    hh_children: ordinal
    hh_cars: ordinal
    hh_bikes: ordinal
    hh_motorcycles: ordinal
  
  evaluation_params:
    split_on: [gender, age, ethnicity, education, license, car_access, work_status]

# VAESeqLSTM_xxlarge:
#   encoder_params:
#     name: "sequence"
#     max_length: 16
#     norm_duration: 1440
#     jitter: 0
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 6
#     hidden_layers: 6
#     hidden_size: 512
#     dropout: 0.2

# DiscLSTM_small:
#   encoder_params:
#     name: "discrete"
#     step_size: 5
#     duration: 1440
#     jitter: 0
#   model_params:
#     name: "Koushik"
#     latent_dim: 6
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0
#     bidirectional: True

# CVAESeqLSTM_small:
#   encoder_params:
#     name: "sequence"
#     max_length: 16
#     norm_duration: 1440
#     jitter: 0
#   model_params:
#     name: "CVAESeqLSTM"
#     latent_dim: 6
#     hidden_layers: 4
#     hidden_size: 128
#     dropout: 0.2

# CVAESeqLSTM_xxxlarge:
#   encoder_params:
#     name: "sequence"
#     max_length: 16
#     norm_duration: 1440
#     jitter: 0
#   model_params:
#     name: "CVAESeqLSTM"
#     latent_dim: 6
#     hidden_layers: 7
#     hidden_size: 1024
#     dropout: 0.2

CVAESeqLSTM_xxlarge2_r:
  conditionals:
    gender: nominal
    age: nominal
    ethnicity: nominal
    education: nominal
    license: nominal
    car_access: nominal
    work_status: nominal
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0
  model_params:
    name: "CVAESeqLSTM2"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.2

CVAESeqLSTM_xxxlarge2_r:
  conditionals:
    gender: nominal
    age: nominal
    ethnicity: nominal
    education: nominal
    license: nominal
    car_access: nominal
    work_status: nominal
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0
  model_params:
    name: "CVAESeqLSTM2"
    latent_dim: 6
    hidden_layers: 7
    hidden_size: 1024
    dropout: 0.2