global:
  data_path: C:\Users\DAF3\Data\NTS\nts_toy_home_population.csv
  logging_params:
    save_dir: "logs"
    name: "lstm_test"

  seed: 1234

  loader_params:
    train_batch_size: 128
    val_batch_size:  128
    num_workers: 4

  experiment_params:
    LR: 0.005
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.00025
    duration_weight: 10000

  trainer_params:
    max_epochs: 50

small:
  model_params:
    name: "SEQVAESEQ"
    hidden_layers: 16
    hidden_size: 16
    latent_dim: 2
    teacher_forcing_ratio: .5

  encoder_params:
    name: "sequence"
    norm_duration: 1440
    max_length: 10

mid:
  model_params:
    name: "SEQVAESEQ"
    hidden_layers: 32
    hidden_size: 32
    latent_dim: 4
    teacher_forcing_ratio: .5

  encoder_params:
    name: "sequence"
    norm_duration: 1440
    max_length: 10

large:
  model_params:
    name: "SEQVAESEQ"
    hidden_layers: 64
    hidden_size: 64
    latent_dim: 8
    teacher_forcing_ratio: .5

  encoder_params:
    name: "sequence"
    norm_duration: 1440
    max_length: 10


vlarge:
  model_params:
    name: "SEQVAESEQ"
    hidden_layers: 128
    hidden_size: 128
    latent_dim: 16
    teacher_forcing_ratio: .5

  encoder_params:
    name: "sequence"
    norm_duration: 1440
    max_length: 10
