global:
  seed: 1234
  logging_params:
    log_dir: "nudge_logs"
    name: "nudglet"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes.csv"
  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  trainer_params:
    min_epochs: 10
    max_epochs: 100
    patience: 10

  experiment_params:
    LR: 0.0001
    weight_decay: 0.0
    scheduler_gamma: 0.95

  conditionals:
    # gender: nominal
    # age: nominal
    # ethnicity: nominal
    # education: nominal
    # license: nominal
    # car_access: nominal
    work_status: nominal
    # area: nominal
    # income: ordinal
    # hh_size: ordinal
    # hh_composition: nominal
    # hh_children: ordinal
    # hh_cars: ordinal
    # hh_bikes: ordinal
    # hh_motorcycles: ordinal
  
  # evaluation_params:
  #   split_on: [work_status]
  
  encoder_params:
    name: "sequence"
    max_length: 14
    norm_duration: 1440
    jitter: 0.2

# DiscLSTM:
#   encoder_params:
#     name: "discrete"
#     step_size: 5
#     duration: 1440
#     jitter: 0.2
#   model_params:
#     name: "CondDiscLSTM"
#     latent_dim: 6
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.2
#     bidirectional: True

# VAESeqLSTM_kld0:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.0

# VAESeqLSTM_kld0005:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.0005

# VAESeqLSTM_kld005:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.005

# VAESeqLSTM_kld05:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.05

# VAESeqLSTM_kld5:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.5

# CVAESeqLSTM_kld0:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.0

# CVAESeqLSTM_kld0005:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.0005

# CVAESeqLSTM_kld005:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.005

# CVAESeqLSTM_kld05:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.05

# CVAESeqLSTM_kld5:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.5





# VAESeqLSTM_kld0005:
#   model_params:
#     name: "VAESeqLSTM"
#     latent_dim: 128
#     hidden_layers: 8
#     hidden_size: 1024
#     dropout: 0.0
#     kld_weight: 0.0005

# CVAESeqLSTM_kld0005:
#   model_params:
#     name: "CVAESeqLSTM2"
#     latent_dim: 128
#     hidden_layers: 8
#     hidden_size: 1024
#     dropout: 0.0
#     kld_weight: 0.005

CVAESeqLSTM_kld1:
  model_params:
    name: "CVAESeqLSTMDoubleNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.2
    kld_weight: 1

CVAESeqLSTM_kld01:
  model_params:
    name: "CVAESeqLSTMDoubleNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.2
    kld_weight: 0.1

CVAESeqLSTM_kld001:
  model_params:
    name: "CVAESeqLSTMDoubleNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.2
    kld_weight: 0.01

CVAESeqLSTM_kld0001:
  model_params:
    name: "CVAESeqLSTMDoubleNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.2
    kld_weight: 0.001

CVAESeqLSTM_kld00001:
  model_params:
    name: "CVAESeqLSTMDoubleNudge"
    latent_dim: 6
    hidden_layers: 6
    hidden_size: 512
    dropout: 0.2
    kld_weight: 0.0001




# CVAESeqLSTM_kld005_adv1:
#   model_params:
#     name: "CVAESeqLSTMNudgeAdv"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.005
#     adv_weight: 0.1

# CVAESeqLSTM_kld05_adv1:
#   model_params:
#     name: "CVAESeqLSTMNudgeAdv"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.05
#     adv_weight: 0.1

# CVAESeqLSTM_kld005_adv10:
#   model_params:
#     name: "CVAESeqLSTMNudgeAdv"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.005
#     adv_weight: 1.0

# CVAESeqLSTM_kld05_adv10:
#   model_params:
#     name: "CVAESeqLSTMNudgeAdv"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.05
#     adv_weight: 1.0

# CVAESeqLSTM_kld005_adv100:
#   model_params:
#     name: "CVAESeqLSTMNudgeAdv"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.005
#     adv_weight: 10.0

# CVAESeqLSTM_kld05_adv100:
#   model_params:
#     name: "CVAESeqLSTMNudgeAdv"
#     latent_dim: 2
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.0
#     kld_weight: 0.05
#     adv_weight: 10.0

