global:
  logging_params:
    save_dir: "logs_cond"
    name: "test"

  schedules_path: "examples/tmp/nts_home_schedules.csv"
  attributes_path: "examples/tmp/nts_home_attributes.csv"

  loader_params:
    train_batch_size: 256
    val_batch_size:  256
    num_workers: 3

  trainer_params:
    max_epochs: 100

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95
  
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  
  model_params:
    name: "conditional_LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.1
    kld_weight: 0.001

# nts_uncond_1:
#   seed: 1111
#   encoder_params:
#     name: "sequence"
#     max_length: 16
#     norm_duration: 1440
#     jitter: 0.2
#   model_params:
#     name: "LSTM"
#     hidden_layers: 5
#     hidden_size: 128
#     latent_dim: 6
#     dropout: 0.1
#     kld_weight: 0.001


nom1:
  seed: 1111
  conditionals:
    gender: nominal
    age: nominal
    employment: nominal
    education: nominal
    license: nominal
    car_access: nominal


nom2:
  seed: 2222
  conditionals:
    gender: nominal
    age: nominal
    employment: nominal
    education: nominal
    license: nominal
    car_access: nominal

nom3:
  seed: 3333
  conditionals:
    gender: nominal
    age: nominal
    employment: nominal
    education: nominal
    license: nominal
    car_access: nominal

ord1:
  seed: 1111
  conditionals:
    gender: nominal
    age: {ordinal: [0,9]}
    employment: nominal
    education: nominal
    license: nominal
    car_access: nominal


ord2:
  seed: 2222
  conditionals:
    gender: nominal
    age: {ordinal: [0,9]}
    employment: nominal
    education: nominal
    license: nominal
    car_access: nominal

ord3:
  seed: 3333
  conditionals:
    gender: nominal
    age: {ordinal: [0,9]}
    employment: nominal
    education: nominal
    license: nominal
    car_access: nominal