global:
  logging_params:
    save_dir: "logs_cond"
    name: "test"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes.csv"

  loader_params:
    train_batch_size: 256
    val_batch_size:  256
    num_workers: 12

  trainer_params:
    max_epochs: 100
    patience: 10

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95
  
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2

  conditionals:
    gender: nominal
    age: nominal
    employment: nominal
    education: nominal
    license: nominal
    car_access: nominal
  
  evaluation_params:
    split_on: [gender, age, employment, education, license, car_access]

c_1:
  seed: 1111
  model_params:
    name: "C_LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.3
    kld_weight: 0.001

vae_1:
  seed: 1111
  model_params:
    name: "VAE_LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.3
    kld_weight: 0.001

cvae_1:
  seed: 1111
  model_params:
    name: "CVAE_LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.3
    kld_weight: 0.001