global:
  logging_params:
    log_dir: "logs"
    name: "paper_c_rnn_Jvae"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"

  conditionals:
    gender: nominal
    age_group: nominal
    car_access: nominal
    work_status: nominal
    income: nominal

  evaluation_params:
    split_on: [gender, age_group, car_access, work_status, income]

  attribute_encoder: "tokens"

  encoder_params:
    name: "sequence"
    max_length: 12
    norm_duration: 1440
    jitter: 0.1

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

A:
  seed: 11111

B:
  seed: 22222

C:
  seed: 33333

D:
  seed: 44444

E:
  seed: 55555

