global:
  logging_params:
    log_dir: "logs"
    name: "paper_d_cnn_vae"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"

  evaluation_params:
    split_on: [gender, age_group, car_access, work_status, income]

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  encoder_params:
    name: "discrete"
    step_size: 10
    duration: 1440
    jitter: 0.1

paper_d_cnn_vae_nrun0:
  model_params:
    name: "VAEDiscConv"

paper_d_cnn_vae_nrun1:
  model_params:
    name: "VAEDiscConv"

paper_d_cnn_vae_nrun2:
  model_params:
    name: "VAEDiscConv"

paper_d_cnn_vae_nrun3:
  model_params:
    name: "VAEDiscConv"

paper_d_cnn_vae_nrun4:
  model_params:
    name: "VAEDiscConv"