global:
  seed: 1234

  logging_params:
    log_dir: "logs"
    name: "search_d_rnn"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"
  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  trainer_params:
    min_epochs: 40
    max_epochs: 100
    patience: 20

  conditionals:
    gender: nominal
    age_group: nominal
    # ethnicity: nominal
    # education: nominal
    # license: nominal
    car_access: nominal
    work_status: nominal
    # area: nominal
    income: ordinal
    # hh_size: ordinal
    # hh_composition: nominal
    # hh_children: ordinal
    # hh_cars: ordinal
    # hh_bikes: ordinal
    # hh_motorcycles: ordinal
  
  # evaluation_params:
  #   split_on: [work_status]
  

# LR01:
#   experiment_params:
#     LR: 0.01
#     weight_decay: 0.0
#     scheduler_gamma: 0.95
#   encoder_params:
#     name: "discrete"
#     step_size: 10
#     duration: 1440
#     jitter: 0.1
#   model_params:
#     name: "CondDiscLSTM"
#     latent_dim: 0
#     hidden_layers: 2
#     hidden_size: 128
#     dropout: 0.1
#     bidirectional: True

2x64:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
  encoder_params:
    name: "discrete"
    step_size: 10
    duration: 1440
    jitter: 0.1
  model_params:
    name: "CondDiscLSTM"
    latent_dim: 0
    hidden_layers: 2
    hidden_size: 64
    dropout: 0.1
    bidirectional: True

3x64:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
  encoder_params:
    name: "discrete"
    step_size: 10
    duration: 1440
    jitter: 0.1
  model_params:
    name: "CondDiscLSTM"
    latent_dim: 0
    hidden_layers: 3
    hidden_size: 64
    dropout: 0.1
    bidirectional: True

3x128:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
  encoder_params:
    name: "discrete"
    step_size: 10
    duration: 1440
    jitter: 0.1
  model_params:
    name: "CondDiscLSTM"
    latent_dim: 0
    hidden_layers: 3
    hidden_size: 128
    dropout: 0.1
    bidirectional: True
  
4x128:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
  encoder_params:
    name: "discrete"
    step_size: 10
    duration: 1440
    jitter: 0.1
  model_params:
    name: "CondDiscLSTM"
    latent_dim: 0
    hidden_layers: 4
    hidden_size: 128
    dropout: 0.1
    bidirectional: True