global:
  logging_params:
    log_dir: "logs"
    name: "search_d_cnn_vae"

  schedules_path: "tmp/nts_home_schedules.csv"

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  trainer_params:
    min_epochs: 40
    max_epochs: 200
    patience: 20

  seed: 1234

  encoder_params:
    name: "discrete"
    step_size: 10
    duration: 1440
    jitter: 0.1


3x64:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [64,64,64]
    dropout: 0.1

4x64:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [64,64,64,64]
    dropout: 0.1

5x64:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [64,64,64,64,64]
    dropout: 0.1

6x64:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [64,64,64,64,64,64]
    dropout: 0.1

3x128:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [128,128,128]
    dropout: 0.1

4x128:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [128,128,128,128]
    dropout: 0.1

6x128:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [128,128,128,128,128,128]
    dropout: 0.1

3x256:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [256,256,256]
    dropout: 0.1

4x256:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [256,256,256,256]
    dropout: 0.1

5x256:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [256,256,256,256,256]
    dropout: 0.1

6x256:
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.9
    kld_weight: 0.01
  model_params:
    name: "VAEDiscConv"
    latent_dim: 6
    hidden_layers: [256,256,256,256,256,256]
    dropout: 0.1
