global:
  seed: 1234
  logging_params:
    log_dir: "logs"
    name: "search_c_rnn_Jvae4"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"

  conditionals:
    gender: nominal
    age_group: nominal
    # ethnicity: nominal
    # education: nominal
    # license: nominal
    car_access: nominal
    work_status: nominal
    # area: nominal
    income: nominal
    # hh_size: ordinal
    # hh_composition: nominal
    # hh_children: ordinal
    # hh_cars: ordinal
    # hh_bikes: ordinal
    # hh_motorcycles: ordinal

  # evaluation_params:
    # split_on: [gender, age_group, car_access, work_status, income]
    # split_on: [work_status]

  attribute_encoder: "tokens"

  encoder_params:
    name: "sequence"
    max_length: 12
    norm_duration: 1440
    jitter: 0.1

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  trainer_params:
    min_epochs: 40
    patience: 10
    max_epochs: 100

Z6K01H5x256+256LL0001:
  model_params:
    name: "JVAESeqLSTM"
    hidden_n: 5
    hidden_size: 256
    labels_hidden_size: 256
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.5
  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.01
    label_loss_weight: 0.0001

