global:
  schedules_path: "examples/data/synthetic_schedules.csv"
  logging_params:
    save_dir: "logs"
    name: "conditionals_test"
  loader_params:
    train_batch_size: 128
    val_batch_size:  128
    num_workers: 3
  trainer_params:
    max_epochs: 50
  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95

  seed: 1234

unconditional:
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  model_params:
    name: "LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.1
    kld_weight: 0.001

conditional:
  attributes_path: "examples/data/synthetic_attributes.csv"
  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2
  conditionals:
    gender: nominal
    age: {ordinal: [0,100]}
    employment: nominal
  model_params:
    name: "conditional_LSTM"
    hidden_layers: 5
    hidden_size: 128
    latent_dim: 6
    dropout: 0.1
    kld_weight: 0.001