seed: 1234

logging_params:
  log_dir: "logs"
  name: "trans"

schedules_path: "tmp/nts_home_schedules.csv"

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  min_epochs: 20
  max_epochs: 100
  patience: 10

experiment_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.99

encoder_params:
  name: "discrete"
  max_length: 16
  norm_duration: 1440
  jitter: 0

model_params:
  name: "VAEDiscTrans"
  latent_dim: 6
  hidden_n: 2
  hidden_size: 32
  heads: 4
  dropout: 0
  kld_weight: 0.0
