seed: 12345

logging_params:
  log_dir: logs
  name: VAEContXAtt_tune

tune:
  trials: 200
  prune: True
  timeout:  36000 # seconds

schedules_path: tmp/nts_home_schedules.csv
# attributes_path: tmp/nts_home_attributes_groups.csv

# conditionals:
#   gender: nominal
#   age_group: nominal
#   car_access: nominal
#   work_status: nominal
#   income: nominal

# evaluation_params:
#   split_on: [gender, age_group, car_access, work_status, income]

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  min_epochs: 20
  max_epochs: 100
  patience: 10

encoder_params:
  name: "sequence_staggered"
  max_length: 16
  duration: 1440
  jitter: 0

experiment_params:
  LR: suggest_float(LR, 1e-5, 0.1, log=True)
  weight_decay: 0.01
  scheduler_gamma: 0.975
  kld_weight: 0.01

model_params:
  name: VAESeqXAtt
  latent_dim: 6
  hidden_n: suggest_int(hidden_n, 2, 6)
  heads: suggest_int(heads, 4, 8)
  hidden_size: suggest_categorical(hidden_size, [128, 256, 512])
  ffwd_size: suggest_categorical(ffwd_size, [128, 256, 512, 1024])
  dropout: suggest_float(dropout, 0, 0.5)
  embedding: suggest_categorical(embedding, [concat, add])
  position_embedding: suggest_categorical(position_embedding, [none, fixed, learnt])
  time_embedding: suggest_categorical(time_embedding, [none, start, remaining])
  latent_context: suggest_categorical(latent_context, [xattention, add])