seed: 12345

logging_params:
  log_dir: logs
  name: CVAESeqLSTM_tune

tune:
  trials: 200
  prune: True
  timeout:  36000 # seconds

schedules_path: tmp/nts_home_schedules.csv
attributes_path: tmp/nts_home_attributes_groups.csv

attribute_encoder: "tokens"

conditionals:
  gender: nominal
  age_group: nominal
  car_access: nominal
  work_status: nominal
  income: nominal

# evaluation_params:
#   split_on: [gender, age_group, car_access, work_status, income]

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  min_epochs: 20
  max_epochs: 200
  patience: 10

encoder_params:
  name: "sequence"
  max_length: 16
  duration: 1440
  jitter: trial.suggest_float("jitter", 0, 0.3)

experiment_params:
  LR: trial.suggest_float("LR", 1e-4, 0.001, log=True)
  weight_decay: 0.01
  scheduler_gamma: 0.975
  kld_weight: 0.01

model_params:
  name: CVAESeqLSTM
  latent_dim: 6
  hidden_n: trial.suggest_int("hidden_n", 2, 6)
  hidden_size: trial.suggest_categorical("hidden_size", [128, 256, 512, 1024])
  labels_hidden_size: trial.suggest_categorical("labels_hidden_size", [16, 32, 64, 128, 256])
  dropout: trial.suggest_float("dropout", 0, 0.3)
  encoder_conditionality: both
  latent_conditionality: concat
  decoder_conditionality: inputs
