seed: 12345

logging_params:
  log_dir: logs/discrete_models
  name: fc_tune

tune:
  trials: 400
  prune: True
  timeout:  72000 # seconds

schedules_path: tmp/nts_schedules_2023.csv

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  min_epochs: 50
  max_epochs: 150
  patience: 50

encoder_params:
  name: "discrete"
  duration: 1440
  step_size: 10
  jitter: trial.suggest_float("jitter", 0, 0.3)
  weighting: unit
  joint_weighting: unit

experiment_params:
  LR: trial.suggest_float("LR", 1e-4, 0.01, log=True)
  weight_decay: 0.02
  scheduler_gamma: 0.975
  kld_weight: 0.005
  # duration_loss_weight: 200

model_params:
  name: "VAEDiscFC"
  hidden_n: trial.suggest_int("hidden_n", 2, 4)
  hidden_size: trial.suggest_categorical("hidden_size", [32, 64, 128])
  latent_dim: 6
  dropout: trial.suggest_float("dropout", 0, 0.3)
  # teacher_forcing_ratio: 0.5