seed: 12345

logging_params:
  log_dir: logs
  name: CVAEContRNN_tune

tune:
  trials: 200
  prune: True
  timeout:  36000 # seconds

schedules_path: tmp/nts_home_schedules.csv
attributes_path: tmp/nts_home_attributes_groups.csv

conditionals:
  gender: nominal
  age_group: nominal
  car_access: nominal
  work_status: nominal
  income: nominal

attribute_encoder: "tokens"

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  min_epochs: 20
  max_epochs: 100
  patience: 10

experiment_params:
  LR: suggest_float(LR, 1e-5, 0.01, log=True)
  weight_decay: suggest_float(weight_decay, 0, 0.1)
  scheduler_gamma: suggest_float(scheduler_gamma, 0.95, 1)
  kld_weight: 0.001

encoder_params:
  name: "sequence"
  max_length: 16
  norm_duration: 1440
  jitter: 0


model_params:
  name: CVAESeqLSTM
  latent_dim: 6
  hidden_n: suggest_int(hidden_n, 3, 6)
  hidden_size: suggest_categorical(hidden_size, [128, 256, 512, 1024])
  dropout: 0
