seed: 12345

logging_params:
  log_dir: logs
  name: VAEDiscFC_tune

tune:
  trials: 200
  prune: True
  timeout:  36000 # seconds

schedules_path: tmp/nts_home_schedules.csv
attributes_path: tmp/nts_home_attributes_groups.csv

conditionals:
  gender: nominal
  age_group: nominal
  car_access: nominal
  work_status: nominal
  income: nominal

evaluation_params:
  split_on: [gender, age_group, car_access, work_status, income]

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  min_epochs: 20
  max_epochs: 100
  patience: 10

experiment_params:
  LR: suggest_float(LR, 1e-5, 0.01, log=True)
  weight_decay: suggest_float(weight_decay, 0, 0.1)
  scheduler_gamma: suggest_float(scheduler_gamma, 0.95, 1)
  kld_weight: 0.001

encoder_params:
  name: "discrete"
  duration: 1440
  step_size: 10
  jitter: suggest_float(jitter, 0, 0.3)

model_params:
  name: CVAESeqLSTM
  latent_dim: 6
  hidden_n: suggest_int(hidden_n, 1, 3)
  hidden_size: suggest_categorical(hidden_size, [16, 32, 64])
  dropout: suggest_float(dropout, 0, 0.3)