seed: 1234

logging_params:
  log_dir: "logs/timing"
  name: "VAEContLSTM_countdown_none"

# tune:
#   trials: 500
#   prune: True
#   timeout:  100000 # seconds

schedules_path: "tmp/nts_schedules_2023.csv"

loader_params:
  train_batch_size: 1024
  val_batch_size:  1024
  num_workers: 8

trainer_params:
  # detect_anomaly: True
  min_epochs: 20
  max_epochs: 150
  patience: 20

experiment_params:
  LR: 0.0025
  weight_decay: 0.02
  scheduler_gamma: 0.975
  kld_weight: 0.01
  duration_loss_weight: 100
  end_loss_weight: 0
  total_duration_loss_weight: 0

encoder_params:
  name: "continuous"
  fix_durations: "stretch"
  max_length: 16
  duration: 1440
  jitter: 0.0
  weighting: unit
  joint_weighting: unit
  trim_eos: True

# model_params:
#   name: "VAEContLSTMCountdown"
#   latent_dim: 6
#   hidden_n: trial.suggest_int("hidden_n", 2, 4)
#   hidden_size: trial.suggest_categorical("hidden_size", [32, 64, 128, 256])
#   dropout: trial.suggest_categorical("dropout", [0.0, 0.02, 0.05, 0.1, 0.2])
#   normalise_durations: True
#   head_depth: trial.suggest_int("head_n", 1, 4)
#   head_hidden_size: trial.suggest_categorical("head_hidden_size", [4, 8, 16, 32, 64, 128])

model_params:
  name: "VAEContLSTMCountdown"
  latent_dim: 6
  hidden_n: 2
  hidden_size: 128
  dropout: 0
  normalise_durations: True
  head_depth: 2
  head_hidden_size: 16
