data_path: "examples/tmp/nts_toy_population.csv"

logging_params:
  save_dir: "logs"

model_params:
  name: "VAE"
  hidden_dims: [64,64]
  latent_dim: 2
  kernel_size: [3,3]
  stride: [2,2]

encoder_params:
  name: "descrete"
  duration: 1440
  step_size: 10

loader_params:
  train_batch_size: 128
  val_batch_size:  128
  num_workers: 4

experiment_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025

trainer_params:
  max_epochs: 40

seed: 1234
  