global:
  seed: 1234
  logging_params:
    log_dir: "experiments"
    name: "vaes2"

  schedules_path: "tmp/nts_home_schedules.csv"

  loader_params:
    train_batch_size: 512
    val_batch_size:  512
    num_workers: 12

  trainer_params:
    min_epochs: 20
    max_epochs: 100
    patience: 10

  experiment_params:
    LR: 0.001
    weight_decay: 0.0
    scheduler_gamma: 0.95

  encoder_params:
    name: "sequence"
    max_length: 16
    norm_duration: 1440
    jitter: 0.2

VAESeqLSTM_6x6x512_kld0:
  model_params:
    name: "VAESeqLSTM"
    latent_dim: 6
    hidden_n: 6
    hidden_size: 512
    dropout: 0.2
    kld_weight: 0.0
