global:
  seed: 12345

  logging_params:
    log_dir: "logs/foundations2"
    name: "B"
  
  schedules_path: "~/Projects/foundata/output/no_aus_2023/activities.csv"
  attributes_path: "~/Projects/foundata/output/no_aus_2023/binned_attributes.csv"
  synthetic_attributes_path: "~/Projects/foundata/output/nts_2023/binned_attributes.csv"
  
  evaluation_params:
    split_on: [source, year, age, employment, hh_income, hh_zone, day]
    schedules_path: "../foundata/output/nts_2023/activities.csv"
    attributes_path: "../foundata/output/nts_2023/binned_attributes.csv"

  encoder_params:
    name: "continuous"
    max_length: 16
    norm_duration: 1440
    jitter: 0
    fix_durations: stretch
    trim_eos: True
    weighting: unit
    joint_weighting: unit

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8
    val_split: 0.1
    test_split: 0.1

  trainer_params:
    min_epochs: 20
    patience: 10
    max_epochs: 100
    beta_scheduling:
      enabled: False
    collapse_monitoring:
      enabled: True
    anchor_scheduling:
      enabled: True
      warmup_epochs: 10
      start_alpha: 0.0
      end_alpha: 1.0
    prior_separation_monitoring:
      enabled: True

  experiment_params:
    LR: 0.001
    weight_decay: 0.01
    scheduler_gamma: 0.98
    kld_weight: 0.01
    duration_loss_weight: 200


no_aus_2023_all:
  labels_encoder:
    name: "table"
    weighting: unit
    joint_weighting: inverse
    labels:
      source: nominal
      year: nominal
      age: nominal
      # sex: nominal
      employment: nominal
      hh_income: nominal
      hh_zone: nominal
      day: nominal
      # vehicles: nominal
      # access_egress_distance: nominal
  model_params:
    name: "CVAEContLSTMCP"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.0
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: none
    label_encoder: concat

no_aus_2023_table_encoder:
  labels_encoder:
    name: "table"
    weighting: unit
    joint_weighting: inverse
    labels:
      source: nominal
      year: nominal
      age: nominal
      # sex: nominal
      employment: nominal
      hh_income: nominal
      hh_zone: nominal
      day: nominal
      # vehicles: nominal
      # access_egress_distance: nominal
  model_params:
    name: "CVAEContLSTMCP"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.5
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: none

no_aus_2023_no_forcing:
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      source: nominal
      year: nominal
      age: nominal
      # sex: nominal
      employment: nominal
      hh_income: nominal
      hh_zone: nominal
      day: nominal
      # vehicles: nominal
      # access_egress_distance: nominal
  model_params:
    name: "CVAEContLSTMCP"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.0
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: none

no_aus_2023_film_labels:
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      source: nominal
      year: nominal
      age: nominal
      # sex: nominal
      employment: nominal
      hh_income: nominal
      hh_zone: nominal
      day: nominal
      # vehicles: nominal
      # access_egress_distance: nominal
  model_params:
    name: "CVAEContLSTMCP"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.5
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: none
    label_encoder: film

no_aus_2023_decoder_outputs_injection:
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      source: nominal
      year: nominal
      age: nominal
      # sex: nominal
      employment: nominal
      hh_income: nominal
      hh_zone: nominal
      day: nominal
      # vehicles: nominal
      # access_egress_distance: nominal
  model_params:
    name: "CVAEContLSTMCP"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.5
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: inputs

no_aus_2023_film_all_labels:
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      source: nominal
      year: nominal
      age: nominal
      # sex: nominal
      employment: nominal
      hh_income: nominal
      hh_zone: nominal
      day: nominal
      # vehicles: nominal
      # access_egress_distance: nominal
  model_params:
    name: "CVAEContLSTMCP"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.5
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: none
    label_encoder: per_label_film

no_aus_2023_add_labels:
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      source: nominal
      year: nominal
      age: nominal
      # sex: nominal
      employment: nominal
      hh_income: nominal
      hh_zone: nominal
      day: nominal
      # vehicles: nominal
      # access_egress_distance: nominal
  model_params:
    name: "CVAEContLSTMCP"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0.0
    teacher_forcing_ratio: 0.5
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: inputs