global:
  seed: 12345

  logging_params:
    log_dir: "logs/foundations"
    name: "E2"
  
  synthetic_attributes_path: "tmp/foundation/experiment_e/target_attributes.csv"
  
  evaluation_params:
    # split_on: [day, employment, avg_speed, age, hh_income]
    split_on: [day, hh_zone, avg_speed, age]
    schedules_path: "tmp/foundation/experiment_e/target_activities.csv"
    attributes_path: "tmp/foundation/experiment_e/target_attributes.csv"

  encoder_params:
    name: "continuous"
    max_length: 16
    norm_duration: 1440
    jitter: 0
    fix_durations: stretch
    trim_eos: True
    weighting: unit
    joint_weighting: unit

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8
    val_split: 0.1
    test_split: 0.1

  trainer_params:
    min_epochs: 5
    min_steps: 1000
    max_epochs: 100
    max_steps: 20000
    max_time: "00:00:10:00"
    patience: 25

  model_params:
    name: "CVAEContLSTM"
    hidden_n: 4
    hidden_size: 256
    labels_hidden_size: 64
    latent_dim: 6
    dropout: 0
    teacher_forcing_ratio: 0.5
    hidden_conditionality: add
    encoder_conditionality: none
    latent_conditionality: add
    decoder_conditionality: none

  experiment_params:
    LR: 0.001
    weight_decay: 0.02
    scheduler_gamma: 0.975
    kld_weight: 0.01
    duration_loss_weight: 200

baseline:
  schedules_path: "tmp/foundation/experiment_e/target_activities.csv"
  attributes_path: "tmp/foundation/experiment_e/target_attributes.csv"
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      sex: nominal
      day: nominal
      hh_zone: nominal
      # access_egress_distance: nominal
      avg_speed: nominal
      age: nominal
      hh_income: nominal
      # source: nominal
      # year: nominal


aus:
  schedules_path: "tmp/foundation/experiment_e/qhts_activities.csv"
  attributes_path: "tmp/foundation/experiment_e/qhts_attributes.csv"
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      sex: nominal
      day: nominal
      hh_zone: nominal
      # access_egress_distance: nominal
      avg_speed: nominal
      age: nominal
      hh_income: nominal
      # source: nominal
      # year: nominal


western:
  schedules_path: "tmp/foundation/experiment_e/western_activities.csv"
  attributes_path: "tmp/foundation/experiment_e/western_attributes.csv"
  labels_encoder:
    name: "tokens"
    weighting: unit
    joint_weighting: inverse
    labels:
      sex: nominal
      day: nominal
      hh_zone: nominal
      # access_egress_distance: nominal
      avg_speed: nominal
      age: nominal
      hh_income: nominal
      # source: nominal
      # year: nominal


# western2:
#   schedules_path: "tmp/foundation/experiment_e/western2_activities.csv"
#   attributes_path: "tmp/foundation/experiment_e/western2_attributes.csv"
#   labels_encoder:
#     name: "tokens"
#     weighting: unit
#     joint_weighting: inverse
#     labels:
#       sex: nominal
#       day: nominal
#       hh_zone: nominal
#       # access_egress_distance: nominal
#       avg_speed: nominal
#       age: nominal
#       hh_income: nominal
#       # source: nominal
#       # year: nominal
