name: Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - CONTRIBUTING.md
      - docs/**
      - mkdocs.yml

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        py3version: ["9", "11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: caveat
          create-args: >-
            python=3.${{ matrix.py3version }}
            -c conda-forge -c pytorch -c nvidia -c city-modelling-lab
            --file=requirements/base.txt
            --file=requirements/dev.txt
          cache-environment: true
          post-cleanup: none

      - name: Install package
        run: pip install acteval

      - name: Install package
        run: pip install --no-deps -e .

      - name: Run tests
        run: pytest --no-cov

  test-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: caveat
          create-args: >-
            python=3.11
            -c conda-forge -c pytorch -c nvidia -c city-modelling-lab
            --file=requirements/base.txt
            --file=requirements/dev.txt
          cache-environment: true
          post-cleanup: none

      - name: Install acteval
        run: pip install acteval
        
      - name: Install package
        run: pip install --no-deps -e .

      - name: Run tests with coverage
        run: pytest tests/

      - uses: codecov/codecov-action@v4
        with:
          file: reports/coverage/coverage.xml
